name: GeoSpark
favicon: null
layout_spectrum: 0.6639571911655366
typography_spectrum: 0.2635778859257698
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.2607618775218725
  lightness: 0.5292734769172966
  saturation: 0.7441601571626961
  rhythmicContrast: 0.2761962048243731
purpose: []
